/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as WriteupsSlugRouteImport } from './routes/writeups.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteupsSlugRoute = WriteupsSlugRouteImport.update({
  id: '/writeups/$slug',
  path: '/writeups/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archives': typeof ArchivesRoute
  '/categories': typeof CategoriesRoute
  '/tags': typeof TagsRoute
  '/writeups/$slug': typeof WriteupsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archives': typeof ArchivesRoute
  '/categories': typeof CategoriesRoute
  '/tags': typeof TagsRoute
  '/writeups/$slug': typeof WriteupsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archives': typeof ArchivesRoute
  '/categories': typeof CategoriesRoute
  '/tags': typeof TagsRoute
  '/writeups/$slug': typeof WriteupsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/archives' | '/categories' | '/tags' | '/writeups/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/archives' | '/categories' | '/tags' | '/writeups/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archives'
    | '/categories'
    | '/tags'
    | '/writeups/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchivesRoute: typeof ArchivesRoute
  CategoriesRoute: typeof CategoriesRoute
  TagsRoute: typeof TagsRoute
  WriteupsSlugRoute: typeof WriteupsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writeups/$slug': {
      id: '/writeups/$slug'
      path: '/writeups/$slug'
      fullPath: '/writeups/$slug'
      preLoaderRoute: typeof WriteupsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchivesRoute: ArchivesRoute,
  CategoriesRoute: CategoriesRoute,
  TagsRoute: TagsRoute,
  WriteupsSlugRoute: WriteupsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
